[package]
name = "diffr"
version = "0.1.0"
authors = ["Nathan Moreau <nathan.moreau@m4x.org>"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
termcolor = "1"
clap = "2.33.0"
atty = "0.2"
